// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/monitoring.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 851301952407450784),
      name: 'Monitoring',
      lastPropertyId: const obx_int.IdUid(6, 7446783310861797552),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 549101996199909979),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2526788366081213485),
            name: 'timestamp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1177108877939218587),
            name: 'value',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7446783310861797552),
            name: 'type',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 8198340301061631966),
      lastIndexId: const obx_int.IdUid(4, 3196916808360446343),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [3379853569254122654, 8198340301061631966],
      retiredIndexUids: const [
        2549160126166909574,
        1834665352272738720,
        3196916808360446343
      ],
      retiredPropertyUids: const [
        4753168378238574907,
        4151117916561873223,
        8699853480221488783,
        3750784195594740531,
        3382582776848602159,
        7887732355111523068
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Monitoring: obx_int.EntityDefinition<Monitoring>(
        model: _entities[0],
        toOneRelations: (Monitoring object) => [],
        toManyRelations: (Monitoring object) => {},
        getId: (Monitoring object) => object.id,
        setId: (Monitoring object, int id) {
          object.id = id;
        },
        objectToFB: (Monitoring object, fb.Builder fbb) {
          final timestampOffset = fbb.writeString(object.timestamp);
          final typeOffset =
              object.type == null ? null : fbb.writeString(object.type!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, timestampOffset);
          fbb.addInt64(2, object.value);
          fbb.addOffset(5, typeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timestampParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final valueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final object = Monitoring(
              timestamp: timestampParam, value: valueParam, type: typeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Monitoring] entity fields to define ObjectBox queries.
class Monitoring_ {
  /// See [Monitoring.id].
  static final id =
      obx.QueryIntegerProperty<Monitoring>(_entities[0].properties[0]);

  /// See [Monitoring.timestamp].
  static final timestamp =
      obx.QueryStringProperty<Monitoring>(_entities[0].properties[1]);

  /// See [Monitoring.value].
  static final value =
      obx.QueryIntegerProperty<Monitoring>(_entities[0].properties[2]);

  /// See [Monitoring.type].
  static final type =
      obx.QueryStringProperty<Monitoring>(_entities[0].properties[3]);
}
